### ISSUE TITLE
sscanf not defined in xusb.py

### ISSUE THREAD

**Issue by mcuee** [karpierz/libusb#6]
```
(py39venv) C:\work\libusb\pylibusb\examples [master ≡]> python .\xusb.py 04d8:fa2e
Traceback (most recent call last):
  File "C:\work\libusb\pylibusb\examples\xusb.py", line 1198, in <module>
    sys.exit(main())
  File "C:\work\libusb\pylibusb\examples\xusb.py", line 1135, in main
    if sscanf(argv[j], "%x:%x" , ct.pointer(tmp_vid), ct.pointer(tmp_pid)) != 2:
NameError: name 'sscanf' is not defined
```

**Comment by karpierz** [comment]
Fixed in: 1.0.24b1 (2021-11-10) - but still some examples (e.g. xusb.py) don't work properly.
