### ISSUE TITLE
Can't import libusb

### ISSUE THREAD

**Issue by EdelMacias** [karpierz/libusb#9]
Hi, I'm facing an issue when trying to import libusb (python 3.8)

Traceback (most recent call last):
  File "/home/orangepi/chafon/UsbDemo.py", line 6, in <module>
    import libusb
  File "/home/orangepi/.local/lib/python3.8/site-packages/libusb/__init__.py", line 9, in <module>
    from ._libusb import *  # noqa
  File "/home/orangepi/.local/lib/python3.8/site-packages/libusb/_libusb.py", line 32, in <module>
    from ._dll      import dll
  File "/home/orangepi/.local/lib/python3.8/site-packages/libusb/_dll.py", line 10, in <module>
    raise exc
  File "/home/orangepi/.local/lib/python3.8/site-packages/libusb/_dll.py", line 8, in <module>
    dll = DLL(DLL_PATH)
  File "/usr/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/orangepi/.local/lib/python3.8/site-packages/libusb/_platform/_linux/x64/libusb-1.0.so: cannot open shared object file: No such file or directory

The file exists and has read access for everyone, so I'm not sure what is happening. This is on Ubuntu 20.04

**Comment by karpierz** [comment]
Could you please try the last version 1.0.26b4?

**Comment by karpierz** [comment]
I'v checked on WSL'2 Ubuntu 20.04 and it works and tests/stress.py is passed.

**Comment by karpierz** [comment]
I'v checked on WSL'2 Ubuntu 20.04 and it works and tests/stress.py is passed.
If does not work on your env. , please let me know/reopen this issue.
